192.168.1.0 ; 
Networks:
EndNetworks
ZsaznaurzYennBByr3nrpg==
administrator
allowMaster = false
allowDiff = false
MasterPC: 26
C:\Users\Administrator\Documents\
Filter from: 
Filter to:
PC base: PC
PC base fixed: true
Initial root: C:\Users\Neville\Google Drive\MSVC\SecureRemote2
